AndromediaProductionsRemake/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

admin.site.site_header = "Andromedia Productions"
admin.site.site_title = "Andromedia Productions Portal"
admin.site.index_title = "Welcome to Andromedia Productions"

urlpatterns = [
    path('control-panel/', admin.site.urls),
    path('user/', include('user.urls')),
    path('video/', include('video.urls')),
    path('', views.home, name='home'),
    path('play-video/<str:video_id>/', views.video_play, name='video_play')
]

user/urls.py
from django.urls import path

app_name = 'user'

urlpatterns = [

]

video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns = [
    path('import-all/<str:channel_id>/', views.import_all, name='import_all'),
    path('channel/<str:channel_id>/',
         views.ChannelVideosView.as_view(), name='video_channel'),
    path('playlist/<str:playlist_id>/',
         views.PlaylistVideosView.as_view(), name='video_playlist'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.conf import settings


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """Creates and saves a new user"""

        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(
            email=self.normalize_email(email),
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        """Creates and saves a new super user"""

        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that supports using email instead of username"""

    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    def create(self, validated_data):
        user = User(email=validated_data['email'],
                    username=validated_data['username'])
        user.set_password(validated_data['password'])
        user.save()
        return user


class UploadingUser(models.Model):

    user = models.OneToOneField(
        'User', on_delete=models.CASCADE, related_name='uploadingusers')

    channel_id = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.user.email}--{self.channel_id}'

video/models.py
from django.db import models
from django.conf import settings


class Video(models.Model):

    uploading_user = models.ForeignKey('user.UploadingUser',
                                       on_delete=models.CASCADE)
    video_id = models.CharField(max_length=255, blank=False, unique=True)
    image_url = models.URLField(blank=False)
    like = models.PositiveIntegerField(default=0)
    dislike = models.PositiveIntegerField(default=0)
    playlist = models.ForeignKey(
        'video.Playlist', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.video_id}--{self.uploading_user.user.email}'


class Playlist(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    playlist_id = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f'{self.playlist_id}--{self.user.email}'

AndromediaProductionsRemake/views.py
from django.shortcuts import render
from video import models as vid_models
import random
from user.models import UploadingUser


def home(request):

    playlists = vid_models.Playlist.objects.all().filter(
        user__email__exact='traversymedia@gmail.com')

    channel_id = UploadingUser.objects.get(
        user__email__exact='traversymedia@gmail.com').channel_id

    videos = vid_models.Video.objects.all()
    videos = random.sample(list(videos), 50)
    return render(request, 'home.html', {'videos': videos, 'playlists': playlists, 'channel_id': channel_id})


def video_play(request, video_id):
    return render(request, 'video_play.html', {'video_id': video_id})


def fault(request):
    return render(request, 'fault.html')

user/views.py
from django.shortcuts import render

# Create your views here.

video/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from apiclient.discovery import build
from . import models
from django.views import generic
# Create your views here.


def import_all(request, channel_id):
    api_key = "AIzaSyDahUDOnXFAW0jlIC-gIc1cKt_tLlOXzf4"
    youtube = build('youtube', 'v3', developerKey=api_key)
    res = youtube.channels().list(id=channel_id, part='contentDetails').execute()
    playlist_id = res['items'][0]['contentDetails']['relatedPlaylists']['uploads']
    print(playlist_id)

    videos = []
    next_page_token = None

    while(True):
        res = youtube.playlistItems().list(playlistId=playlist_id, part='snippet',
                                           maxResults=50, pageToken=next_page_token).execute()
        items = res['items']
        for item in items:
            videos.append(item['snippet']['resourceId']['videoId'])
        next_page_token = res.get('nextPageToken')

        if next_page_token is None:
            break

    for video in videos:
        try:
            models.Video.objects.create(
                uploading_user=request.user.uploadingusers,
                video_id=video,
                image_url=f'https://img.youtube.com/vi/{video}/sddefault.jpg'
            )
        except:
            continue

    return redirect('admin:video_video_changelist')


class ChannelVideosView(generic.ListView):
    context_object_name = 'videos'
    template_name = 'video/videos_channel.html'
    paginate_by = 20

    def get_queryset(self):
        qs = models.Video.objects.all().filter(
            uploading_user__channel_id__exact=self.kwargs['channel_id'])
        return qs


class PlaylistVideosView(generic.ListView):
    context_object_name = 'videos'
    template_name = 'video/videos_channel.html'
    paginate_by = 20

    def get_queryset(self):
        qs = models.Video.objects.all().filter(
            playlist__playlist_id__exact=self.kwargs['playlist_id'])
        return qs

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Andromedia Productions</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
</head>
<body>
    <a href="{% url 'home' %}">Home</a>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/fault.html
{% extends 'base.html' %}
{% block content %}
<h1>Fault Page</h1>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<br>
Playlists <br>
{% for p in playlists %}
<a href={% url 'video:video_playlist' playlist_id=p.playlist_id %}><li>{{p.name}}</li></a>
{% endfor %}
Channel Name: <a href={% url 'video:video_channel' channel_id=channel_id %}>Traversy Media</a>
<br>
{% for video in videos %}
<a href="{% url 'video_play' video_id=video.video_id %}" target="_blank">
    <img src={{video.image_url}} height="100" width="100"/>
</a>
{% endfor %}
{% endblock content %}

templates/video_play.html
{% extends 'base.html' %}
{% block content %}
<iframe src="https://www.youtube.com/embed/{{video_id}}?autoplay=1" frameborder="0" width="100%" height="300px">
</iframe>
{% endblock content %}

video/templates/video/videos_channel.html
{% extends 'base.html' %}
{% block content %}
    <ul>
        {% for video in videos %}
            <a href="{% url 'video_play' video_id=video.video_id %}" target="_blank">
    <img src={{video.image_url}} height="100" width="100"/>
</a>
        {% endfor %}
    </ul>


    {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}


{% endblock content %}